#!/bin/bash
if [[ -f /usr/share/bash-completion/completions/pacman ]]; then
    source /usr/share/bash-completion/completions/pacman
fi
function siterip {
    if [[ $# -ne 2 ]]; then
        echo "Usage: siterip SITE NAME"
        return 2
    fi
    if [[ ! -d $2 ]]; then
        mkdir $2
    fi
    cd $2
    wget -cpk -nc -nv -np -rl0 "$1"
    cd ..
}

function pacin {
    sudo $PACMAN -S $@
}

function pacrm {
    sudo pacman -Rscu $@
}

function pacsearch {
    $PACMAN -Ss $@ | less 
}

function pacshow {
    $PACMAN -Si $@
}

function pacup {
    sudo $PACMAN -Su --noconfirm
}

function pacup-force {
    sudo $PACMAN -Syyu
}

function pacorphan {
    ORPHANS=$(pacman -Qqtd)
    if [[ -n "$ORPHANS" ]]; then
        sudo pacman -Rcsu $ORPHANS
    fi
}

function paclist {
    if [[ -n "$2" ]]; then
        pacman -Ql $1 | grep -e $2
    else
        pacman -Ql $1
    fi
}

function pacowns {
    pacman -Qo $@
}

_available(){
    local cur opts prev
    COMPREPLY=()
    _get_comp_words_by_ref cur prev
    _pacman_pkg Slq
}

_installed(){
    local cur opts prev
    COMPREPLY=()
    _get_comp_words_by_ref cur prev
    _pacman_pkg Qq
}

complete -F _installed pacrm
complete -F _available pacin
complete -F _available pacshow
complete -F _installed paclist

aur_update() {
    if [[ -z $(type -P packer) ]]; then
        echo "Packer required"
        return 0
    fi
    if [[ -z $(type -P aurploader) ]]; then
        pacin aurploader
    fi
    cd /tmp
    for i in $*; do
        packer -G $i
        cd $i
        /usr/bin/makepkg -s
        makepkg --source
        aurploader -k *.src.*
        cd ..
        rm -rf $i
    done
    pacorphan
}

service() {
    if [ -z "$1"  -o  -z "$2" ]; then
        echo "Usage: service SERVICE start|stop|restart"
        return 2
    fi
    if [ "$2" != "start" -a  "$2" != "stop" -a  "$2" != "restart" ]; then
        echo "Usage: service SERVICE start|stop|restart"
        return 2
    fi
    sudo /etc/rc.d/$1 $2
}

_services() {
    local cur prev
    _get_comp_words_by_ref cur prev
    if [[ "$prev" == "service" ]]; then
        complist=$(find /etc/rc.d/ -executable -type f | sed 's-/etc/rc.d/--')
        COMPREPLY=($(compgen -W "$complist" -- "$cur"))
    elif [[ -x "/etc/rc.d/$prev" ]]; then
        COMPREPLY=($(compgen -W "start stop restart" -- "$cur"))
    fi
}
complete -F _services service


sync_clip() {
    rsync -av --del $HOME/music/ /media/Clip/MUSIC/
#    rsync -av --ignore-existing --del $HOME/music/ /media/Clip/MUSIC/
}

engage() {
    if [[ -n "$(type -P play)" ]]; then
        play -n synth whitenoise band -n 100 24 band -n 300 100 gain +20
    else
        echo "I cannae do it Captain! I just don't have the power! Also, install sox"
    fi
}
