#! /bin/bash
alias ls='ls -hF --color=auto --group-directories-first'
alias sl='ls'
alias grep='grep --color=auto'
alias less='less -r'
alias powertop='sudo powertop'
alias service='sudo systemctl'
alias makepkg='makepkg -si'
alias df='df -h'
alias du='du -h'
alias large='du -ad1 | head -n-1 | sort -hr | head'
alias ps='ps --forest'
alias serve='python -m http.server'
alias pandoc='pandoc -S --normalize --latex-engine=xelatex'
alias grub_regen='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias mplayer='mplayer -idx -framedrop'
alias bedtime='sudo shutdown -hP +90'
alias notebook='ipython notebook --pylab=inline'
alias blogserve='(cd ~/code/blog/ && bundle exec jekyll serve -w --drafts)'
alias vimroom='vim -c VimroomToggle'
[[ -n "$(type -P vim)" ]] && alias view='vim -R'

if [[ -f /usr/share/bash-completion/completions/systemctl ]]; then
    source /usr/share/bash-completion/completions/systemctl
    complete -F _systemctl service
fi
