#!/bin/bash
if [[ -f /usr/share/bash-completion/completions/pacman ]]; then
    source /usr/share/bash-completion/completions/pacman
fi
function siterip {
    if [[ $# -ne 2 ]]; then
        echo "Usage: siterip SITE NAME"
        return 2
    fi
    if [[ ! -d $2 ]]; then
        mkdir $2
    fi
    cd $2
    wget -pk -nc -rl0 "$1"
    cd ..
}

function pacin {
    sudo $PACMAN -S $@
}

function pacrm {
    sudo pacman -Rscu $@
}

function pacsearch {
    if [[ -n "$(type -P unbuffer)" ]]; then
        unbuffer $PACMAN -Ss $@ | less
    else
        echo "Install expect for color!"
        $PACMAN -Ss $@ | less 
    fi
}

function pacshow {
    $PACMAN -Si $@
}

function pacup {
    sudo $PACMAN -Su --noconfirm
}

function pacup-force {
    sudo $PACMAN -Syyu --noconfirm --devel
}

function pacorphan {
    ORPHANS=$(pacman -Qqtd)
    if [[ -n "$ORPHANS" ]]; then
        sudo pacman -Rcsu $ORPHANS
    fi
}

function paclist {
    if [[ -n "$2" ]]; then
        pacman -Ql $1 | grep -e $2
    else
        pacman -Ql $1
    fi
}

function pacowns {
    pacman -Qo $@
}

_available(){
    local cur opts prev
    COMPREPLY=()
    _get_comp_words_by_ref cur prev
    _pacman_pkg Slq
}

_installed(){
    local cur opts prev
    COMPREPLY=()
    _get_comp_words_by_ref cur prev
    _pacman_pkg Qq
}

complete -F _installed pacrm
complete -F _available pacin
complete -F _available pacshow
complete -F _installed paclist

_require(){
    if [[ -z $(type -P $1) ]]; then
        echo "$1 required"
        return 0
    fi

}

aur_update() {
    _require packer
    _require aurploader
    cd /tmp
    for i in $*; do
        packer -G $i
        cd $i
        /usr/bin/makepkg -s
        makepkg --source
        aurploader -k *.src.*
        cd ..
        rm -rf $i
    done
    pacorphan
}

_sync_dir() {
    _require rsync
    rsync -avm --ignore-existing --del $1 $2
}

sync_clip() {
    _require gpo
    if [[ ! -d /media/Clip ]]; then
        echo "Clip not mounted at /media/Clip"
        return 1
    fi
    _sync_dir $HOME/music/ /media/Clip/MUSIC/
    _sync_dir $HOME/audio/ /media/Clip/AUDIOBOOKS/
    gpo sync

}

engage() {
    if [[ -n "$(type -P play)" ]]; then
        play -n synth whitenoise band -n 100 24 band -n 300 100 gain +20
    else
        echo "I cannae do it Captain! I just don't have the power! Also, install sox"
    fi
}

scratchpad() {
    $(cd /tmp && notebook)
}

clean_root() {
    pacorphan
    sudo pacman -Sc
}

pyproj() {
    if [[ -n $1 ]]; then
        wget -O- https://github.com/pypa/sampleproject/archive/master.tar.gz | tar -xz
        if [[ ! -d $1 ]]; then
            mkdir $1;
        fi
        cp -r sampleproject-master/* $1
        rm -r sampleproject-master
    else
        echo "USAGE: pyproj NAME"
    fi
}

page(){
    if [[ -n "$(type -P unbuffer)" ]]; then
        unbuffer $@ | less
    else
        echo "Install expect for color!" 
        $@ | less
    fi
}
